# Generated by Django 4.2.5 on 2023-11-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logo',
        ),
    ]
