# Generated by Django 4.2.5 on 2023-11-11 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_district_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
