# Generated by Django 4.2.5 on 2023-11-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_district_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
