# Generated by Django 4.2.5 on 2023-11-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_city_country_person_remove_employee_deptid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
